//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterClaim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public int id { get; set; }
        public string DiseaseCode { get; set; }
        public string DiseaseName { get; set; }
    }
}
